### ISSUE TITLE
projectile travel speed should be greater than charecter speeds

### ISSUE THREAD

**Issue by quample** [BenJLubrano/Space-Shooter#48]
In the current version of the game the projectile's travel speed is well below the npc and character speeds. This leads to the players ship accelerating faster than the laser projectiles. It would be more "realistic" if the projectile speeds would always be proportionally faster than the max ship speeds.
This should be a simple fix:)

Also if seeker missiles are implemented; then the ship could out maneuver them using turns but in a straight run the missile would always be faster.

**Comment by BenJLubrano** [comment]
For reference: When the projectile speed is set to 12, it matches the player's speed.
Player weapon "Blaster" speed increased from 15 -> 20
NPC weapon "SlowBlaster" speed increased from 10->15

The range on the blasters is still at 25. So, if the player follows the projectiles, it is possible to see them disappear. 
One potential fix for this is for player projectiles to have unlimited range, and simply be destroyed on reaching a border that matches the edge of their screen (though this wouldn't be very realistic), or simply making the projectiles even faster, but this is not such a good idea for the enemies, since it will make fighting them very hard.

**Comment by quample** [comment]
I think the range is perfect as is. As for the disappearing laser beam, we could just add an animation for the projectile to "vanish" rather than disappear all together. What do you think @BenJLubrano ?

**Comment by BenJLubrano** [comment]
That would be cool. However that would be a larger issue. This one is merged so I'm going to close the issue, but we can continue this discussion on Discord

**Comment by quample** [comment]
Sure.... maybe @elvelasquezm could look into it
