### ISSUE TITLE
Integration of Explosion Animation

### ISSUE THREAD

**Issue by BenJLubrano** [BenJLubrano/Space-Shooter#61]
The explosion animations we have need to be added to the ship. The best way to do this will be to create a new box in the animator for "DefaultShipAnimator", labeled "Explode" or something similar.

The box will transition from "Any State" and the trigger should be "isDead", which is found on the Ship.cs script. (Basically, when the ship dies, and sets isDead to true, it should also set the "isDead" trigger on the animator component to true)

**Comment by BenJLubrano** [comment]
Assigned this only to art since it mostly has to do with visuals

**Comment by BenJLubrano** [comment]
If time permits, it would also be quite cool to get the shield animation working. This will probably have to be on a separate GameObject that is attached to the player, since we don't want the shield animation replacing the player ship animations.

**Comment by cleung0305** [comment]
I have been playing around with making Explosion as an animator for every
ship. this works fine with the enemy ships since they got destroyed right
after the explosion. however it is kinda weird on the player ship. I can't
figure out the time between the explosion and respawn. the ship always
respawns while exploding(and can't move), then back to normal after a split
second.

I believe making the explosion a gameobject is still a better idea. that
way we don't have to worry about changing animation state for the ships. as
well as we can add some other animator for ships as they explode later on.

**Comment by BenJLubrano** [comment]
Closing this issue, though it would still be possible to make it an animation, it really is not important in the long run unless we are going to have huge battles with a lot of explosions. This could potentially cause too many GameObjects instantiated, but we would likely run into issues with projectiles far before this.
